name: main
on:
  workflow_dispatch:
jobs:
  main:
    env:
        GH_TOKEN: ${{github.token}}
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash nb.sh
      - run: gh release create ${{github.run_number}} sw.txt
